/*
  Copyright (c), 2022 - NUTES - Nucleo de Tecnologias Estrategicas na Saude
  http://nutes.uepb.edu.br/
  All rights reserved.
*/

#ifndef SYSTEMTASKS_H
#define SYSTEMTASKS_H

/* Defines */

/* Task Stack Size */
#define APP_DEFAULT_STACK_SIZE 3000
#define APP_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define BUZZER_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define DOOR_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define LEDS_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define FACTORY_BUTTON_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define FACTORY_RESET_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define RFID_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define RTC_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define CONFIG_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define MMU_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define DOOR_SENSOR_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define NETWORK_TASK_STACK_SIZE 5000

#define LIGHT_SENSOR_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE

/* Task Priority */
#define APP_TASK_PRIORITY 1
#define BUZZER_TASK_PRIORITY 2
#define DOOR_TASK_PRIORITY 1
#define LEDS_TASK_PRIORITY 3
#define FACTORY_BUTTON_TASK_PRIORITY 4
#define FACTORY_RESET_TASK_PRIORITY 1
#define RFID_TASK_PRIORITY 5
#define RTC_TASK_PRIORITY 4
#define CONFIG_TASK_PRIORITY 5
#define MMU_TASK_PRIORITY 5
#define NETWORK_TASK_PRIORITY 1
#define DOOR_SENSOR_TASK_PRIORITY 1
#define LIGHT_SENSOR_TASK_PRIORITY 1

/* Tasks Core */
#define APP_TASK_CORE 0
#define BUZZER_TASK_CORE 0
#define DOOR_TASK_CORE 0
#define LEDS_TASK_CORE 0
#define FACTORY_RESET_TASK_CORE 0
#define FACTORY_BUTTON_TASK_CORE 0
#define RFID_TASK_CORE 0
#define RTC_TASK_CORE 0
#define CONFIG_TASK_CORE 0
#define MMU_TASK_CORE 0
#define NETWORK_TASK_CORE 1
#define DOOR_SENSOR_TASK_CORE 0
#define LIGHT_SENSOR_TASK_CORE 0

/* Tasks Delay */
#define APP_TASK_DELAY_MS 1000
#define BUZZER_TASK_DELAY_MS 500
#define DOOR_TASK_DELAY_MS 500
#define LEDS_TASK_DELAY_MS 1000
#define LEDS_TASK_TEST_DELAY_MS 250
#define FACTORY_BUTTON_TASK_DELAY_MS 10
#define FACTORY_RESET_TASK_DELAY_MS 4000
#define RFID_TASK_DELAY_MS 50
#define RTC_TASK_DELAY_MS 1000
#define CONFIG_TASK_DELAY_MS 1000
#define MMU_TASK_DELAY_MS 1000
#define NETWORK_TASK_DELAY_MS 5000

#define DOOR_SENSOR_TASK_DELAY_MS 1000
#define LIGHT_SENSOR_TASK_DELAY_MS 100

#endif
