/*
  Copyright (c), 2022 - NUTES - Nucleo de Tecnologias Estrategicas na Saude
  http://nutes.uepb.edu.br/
  All rights reserved.
*/

#ifndef VERBOSE_H
#define VERBOSE_H

/* Includes */
#include <Arduino.h>

/* Defines */
#define VERBOSE_OFF 0
#define VERBOSE_ON 1

#define VERBOSE_MODULE_APP VERBOSE_OFF
#define VERBOSE_MODULE_MMU VERBOSE_ON
#define VERBOSE_MODULE_DOOR VERBOSE_OFF
#define VERBOSE_MODULE_LEDS VERBOSE_OFF
#define VERBOSE_MODULE_BUZZER VERBOSE_OFF
#define VERBOSE_MODULE_NETWORK VERBOSE_OFF
#define VERBOSE_MODULE_CONFIG VERBOSE_OFF
#define VERBOSE_MODULE_STATUS VERBOSE_OFF
#define VERBOSE_MODULE_RFID VERBOSE_OFF
#define VERBOSE_MODULE_RTC VERBOSE_OFF
#define VERBOSE_MODULE_USER VERBOSE_OFF
#define VERBOSE_MODULE_LOCAL VERBOSE_OFF
#define VERBOSE_MODULE_EVENT VERBOSE_OFF
#define VERBOSE_MODULE_NTP VERBOSE_OFF
#define VERBOSE_MODULE_BROKER VERBOSE_OFF
#define VERBOSE_MODULE_APP_SERVER VERBOSE_OFF
#define VERBOSE_MODULE_FACTORY VERBOSE_ON

#define VERBOSE_MODULE_DOOR_SENSOR VERBOSE_OFF
#define VERBOSE_MODULE_LIGHT_SENSOR VERBOSE_ON

#define VERBOSE_MODULE_NETWORK_GET VERBOSE_ON
#define VERBOSE_MODULE_NETWORK_POST VERBOSE_ON

#define VERBOSE_MODULE_STEP_APP VERBOSE_OFF
#define VERBOSE_MODULE_STEP_MMU VERBOSE_ON
#define VERBOSE_MODULE_STEP_DOOR VERBOSE_OFF
#define VERBOSE_MODULE_STEP_LEDS VERBOSE_OFF
#define VERBOSE_MODULE_STEP_BUZZER VERBOSE_OFF
#define VERBOSE_MODULE_STEP_NETWORK VERBOSE_ON
#define VERBOSE_MODULE_STEP_CONFIG VERBOSE_OFF
#define VERBOSE_MODULE_STEP_STATUS VERBOSE_OFF
#define VERBOSE_MODULE_STEP_RFID VERBOSE_OFF
#define VERBOSE_MODULE_STEP_RTC VERBOSE_OFF
#define VERBOSE_MODULE_STEP_USER VERBOSE_OFF
#define VERBOSE_MODULE_STEP_LOCAL VERBOSE_OFF
#define VERBOSE_MODULE_STEP_EVENT VERBOSE_OFF
#define VERBOSE_MODULE_STEP_NTP VERBOSE_OFF
#define VERBOSE_MODULE_STEP_BROKER VERBOSE_OFF
#define VERBOSE_MODULE_STEP_APP_SERVER VERBOSE_OFF
#define VERBOSE_MODULE_STEP_FACTORY VERBOSE_ON

#define VERBOSE_MODULE_STEP_DOOR_SENSOR VERBOSE_OFF

#define VERBOSE_TASK_APP VERBOSE_ON
#define VERBOSE_TASK_MMU VERBOSE_OFF
#define VERBOSE_TASK_DOOR VERBOSE_OFF
#define VERBOSE_TASK_LEDS VERBOSE_OFF
#define VERBOSE_TASK_BUZZER VERBOSE_OFF
#define VERBOSE_TASK_NETWORK VERBOSE_ON
#define VERBOSE_TASK_CONFIG VERBOSE_OFF
#define VERBOSE_TASK_STATUS VERBOSE_OFF
#define VERBOSE_TASK_RFID VERBOSE_OFF
#define VERBOSE_TASK_RTC VERBOSE_OFF
#define VERBOSE_TASK_USER VERBOSE_OFF
#define VERBOSE_TASK_LOCAL VERBOSE_OFF
#define VERBOSE_TASK_EVENT VERBOSE_OFF
#define VERBOSE_TASK_NTP VERBOSE_OFF
#define VERBOSE_TASK_BROKER VERBOSE_OFF
#define VERBOSE_TASK_APP_SERVER VERBOSE_OFF
#define VERBOSE_TASK_FACTORY VERBOSE_ON

#define VERBOSE_TASK_DOOR_SENSOR VERBOSE_OFF
#define VERBOSE_TASK_LIGHT_SENSOR VERBOSE_ON

/* Data Types - typedefs, structs, unions and/or enumerated */

/* Public Functions */
void verboseSetup(void);
void verboseInit(void);
void verbose(const String &message, int key);

/* Local Functions */
#ifdef _VERBOSE_

#endif

/* Public Variables */

/* Local Variables */
#ifdef _VERBOSE_

#endif

#endif
